apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp 
spec:
 replicas: 1
 selector:
   matchLabels:
      app: myapp
 template:
   metadata:
     name: myapp 
     labels:
       app: myapp
   spec:
     containers:
     - name: myapp 
       image: quay.io/cprakash2118/famous-quotes
       ports:
       - containerPort: 8000
